# Generated by Django 2.0.6 on 2018-06-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_subject', models.CharField(max_length=200)),
                ('reminder_message', models.TextField(max_length=2000)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('reminder_date', models.DateTimeField(verbose_name='reminder created')),
            ],
        ),
    ]
